services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/bibliotecaetec
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:16
    container_name: postgresdb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: bibliotecaetec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
